### ISSUE TITLE
As a dev I want a documentation about what clientData the browser use

### ISSUE THREAD

**Issue by perki** [pryv/dev-site#23]
Could be rephrased as **"...I want documentation about standard `clientData`"**.

Currently:

```
"clientData": {
  "pryv-browser:charts": {
    "{type}": {  // "mass/kg"
      "settings": {
        "color": "#hex",
        "style": "bar" | "line" | "spline" | "point",
        "transform": "sum" | "average" ,
        "interval": "hourly" | "daily" | "weekly" | "monthly" | "yearly",
        "history": "day" | "week" | "month"
      }
    }
  }
}
```

We need to add `interval: "auto"` which will pick the most appropriate interval according to the displayed timeframe. E.g. day -> hour total, week -> weekday total, month -> day total, year -> month total, custom -> pick according to duration.

**Comment by kschiess** [comment]
clientData is used this way by the Dashboard, which we do not document/ship/support. Do we still need to work on this ticket?

**Comment by perki** [comment]
You are right, this should be moved to the “app-web” documentation and eventually quoted in some “FAQ” or sample client data usage in side documentation
