### ISSUE TITLE
As an API user, I want to be able to subscribe to mail notifications for API changes

### ISSUE THREAD

**Issue by perki** [pryv/dev-site#26]

**Comment by kschiess** [comment]
When we get to it, we'll do this and many other things in communication: we've talked about developer workshops on Wednesday, an idea in the same vein. Can we close this ticket so I don't have to read it once a month when I clean the tickets? I agree that we need to cater to our developers, I just don't agree that this needs to be stored in here.

**Comment by kschiess** [comment]
Has been moved to the Trello backlog after discussion.
