### ISSUE TITLE
Setup script not resolving components/api-server/package.json

### ISSUE THREAD

**Issue by tmodoux** [pryv/dev-site#36]
Running ```make setup``` throws errors when trying to ```npm install```:

* At first, npm install failed because dev-site/package.json was referencing the production branch of service-core, which is not existing anymore :
>     "pryv-service-core": "git+ssh://git@github.com:pryv/service-core.git#production"
We patched this in dev-site/master by referencing service-core/release-1.1 instead.

* Now, npm install still fails with the following error:
```
Installing Node modules from 'package.json' if necessary...

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/pryv-service-core/components/api-server" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thiebaudmodoux/.npm/_logs/2017-11-27T15_58_02_648Z-debug.log
```

**Comment by kebetsi** [comment]
@tmodoux Can you switch to yarn as for our other projects, please?

**Comment by tmodoux** [comment]
@kebetsi ack
